var express = require('express')
var router = express.Router()

// add new routes here
var routes1 = require('./routes/routes_1');
var routes2 = require('./routes/routes_2');
var routes3 = require('./routes/routes_3');
var routes4 = require('./routes/routes_4');
var routes5 = require('./routes/routes_5');
var routes6 = require('./routes/routes_6');
var routes7 = require('./routes/routes_7');
var routes8 = require('./routes/routes_8');
var routes9 = require('./routes/routes_9');
var routes10 = require('./routes/routes_10');
var routes11 = require('./routes/routes_11');
var routes12 = require('./routes/routes_12');
var routes13 = require('./routes/routes_13');
var routes14 = require('./routes/routes_14');
var routes15 = require('./routes/routes_15');
var routes16 = require('./routes/routes_16');
var routes17 = require('./routes/routes_17');
var routes18 = require('./routes/routes_18');
var routes19 = require('./routes/routes_19');
var routes20 = require('./routes/routes_20');
var routes21 = require('./routes/routes_21');
var routes22 = require('./routes/routes_22');
var routes23 = require('./routes/routes_23');
var routes24 = require('./routes/routes_24');
var routes25 = require('./routes/routes_25');
var routes26 = require('./routes/routes_26');
var routes27 = require('./routes/routes_27');
var routes28 = require('./routes/routes_28');
var routes29 = require('./routes/routes_29');
var routes30 = require('./routes/routes_30');
var routes31 = require('./routes/routes_31');
var routes32 = require('./routes/routes_32');
var routes33 = require('./routes/routes_33');
var routes34 = require('./routes/routes_34');
var routes35 = require('./routes/routes_35');
var routes36 = require('./routes/routes_36');
var routes37 = require('./routes/routes_37');
var routes38 = require('./routes/routes_38');
var routes39 = require('./routes/routes_39');
var routes40 = require('./routes/routes_40');
var routes41 = require('./routes/routes_41');
var routes42 = require('./routes/routes_42');
var routes43 = require('./routes/routes_43');
var routes44 = require('./routes/routes_44');
var routes45 = require('./routes/routes_45');
var routes46 = require('./routes/routes_46');
var routes47 = require('./routes/routes_47');
var routes48 = require('./routes/routes_48');
var routes49 = require('./routes/routes_49');
var routes50 = require('./routes/routes_50');
var routes51 = require('./routes/routes_51');
var routes52 = require('./routes/routes_52');
var routes53 = require('./routes/routes_53');
var routes54 = require('./routes/routes_54');

// Route index page
router.use('/third_parties', routes1);
router.use('/third_partiesv2', routes2);
router.use('/third_partiesv3', routes3);
router.use('/volnicsv1', routes4);
router.use('/volnicsv2', routes5);
router.use('/volnicsv3', routes6);
router.use('/spa', routes7);
router.use('/volnicsv4', routes8);
router.use('/volnicsv5', routes9);
router.use('/volnicsv6', routes10);
router.use('/volnicsv7', routes11);
router.use('/volnicsv8', routes12);
router.use('/volnicsv9', routes13);
router.use('/volnicsv10', routes14);
router.use('/volnicsv11', routes15);
router.use('/RREv1', routes16);
router.use('/RREv2', routes17);
router.use('/volnicsv13', routes19);
router.use('/volnicsv1a', routes20);
router.use('/volnicsv14', routes21);
router.use('/volnicsv15', routes22);
router.use('/volnicsv1b', routes23);
router.use('/volnicsv16', routes24);
router.use('/overseasv1', routes25);
router.use('/volnicsv17', routes26);
router.use('/volnicsv18', routes27);
router.use('/volnicsv1a_zoom', routes28);
router.use('/volnicsv19', routes29);
router.use('/overseasv2', routes30);
router.use('/overseasv3', routes31);
router.use('/name_dob', routes32);
router.use('/overseasv4', routes33);
router.use('/volnicsv20', routes34);
router.use('/name_dob2', routes35);
router.use('/volnicsv21', routes36);
router.use('/name_dob3', routes37);
router.use('/name_dob4', routes38);
router.use('/RREv3', routes39);
router.use('/RREv4', routes40);
router.use('/volnicsv22', routes41);
router.use('/welsh', routes42);
router.use('/welsh2', routes43);
router.use('/RREv5', routes44);
router.use('/RREv6', routes45);
router.use('/RREv7', routes46);
router.use('/RREv8', routes47);
router.use('/notifyv1', routes48);
router.use('/notifyv2', routes49);
router.use('/feedback', routes50);
router.use('/feedback2', routes51);
router.use('/third_partiesv4', routes52);
router.use('/volnicsv23', routes53);
router.use('/RREv9', routes54);

module.exports = router